[package]
edition.workspace = true
license.workspace = true
name = "test_libusb"
publish = false
repository.workspace = true
version = "0.1.0"

[dependencies]
crab-usb = {workspace = true, features = ["libusb"]}
env_logger = "0.11"
log = "0.4"
tokio = {version = "1", features = ["full"]}
