[package]
edition.workspace = true
license.workspace = true
name = "uvc-frame-parser"
publish = false
repository.workspace = true
version = "0.1.0"

[dependencies]
log = "0.4"
env_logger = "0.11"
image = "0.24"
tokio = {version = "1", features = ["full"]}
ffmpeg-next = "7.1.0"
